# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wyoon <wyoon@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/14 15:52:36 by wyoon             #+#    #+#              #
#    Updated: 2022/09/14 15:55:23 by wyoon            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc

CFLAGS = -Wall -Werror -Wextra

NAME = ft_display_file

all = $(NAME)

$(NAME) :
	$(CC) $(CFLAGS) $(NAME).c -o $(NAME)

clean :
	rm -rf *.o

fclean :
	rm -rf $(NAME)
